# NOTE: This depends on AWS resources deployed for the "joshbeard.me" website.
# Refer to https://github.com/joshbeard/joshbeard.me-tf-aws
name: Build
on:
  push:
    branches:
      - master
      - refactor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: docker://pandoc/core:2.17
        with:
          args: >
            --from markdown --to html README.md
            -o web/dist/index.html
            -H web/src/_includes/header.html
            -B web/src/_includes/body.html
            -A web/src/_includes/footer.html
            -c assets/css/style.css
            --metadata title="Josh Beard"

      - uses: docker://pandoc/latex
        with:
          args: >
            --from markdown --to docx README.md
            -f gfm
            -o web/dist/Josh-Beard-Resume.docx

      - uses: browser-actions/setup-chrome@latest
      - run: >
          chrome
          -headless
          -disable-gpu
          --no-sandbox
          --print-to-pdf-no-header=web/dist/Josh-Beard-Resume.pdf
          web/dist/index.html

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      - uses: actions/upload-artifact@master
        with:
          name: src
          path: |
            web/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: src
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
            --exclude ".git\*"
            --exclude ".gitlab-ci.yml"
            --exclude ".gitignore"
            --exclude "Makefile"
            --exclude "README.md"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '.'
          DEST_DIR: "resume/"

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}
          PATHS: "/resume/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}